### ISSUE TITLE
SceneCache circular dependencies

### ISSUE THREAD

**Issue by Teashrock** [deep-entertainment/egoventure#18]
![image](https://user-images.githubusercontent.com/12483854/131160254-f40205d8-bba2-4616-97a2-c5eb9ed97973.png)
![image](https://user-images.githubusercontent.com/12483854/131160515-8cd97a21-7b68-47bb-a6be-a6b1da8458b9.png)

**Comment by MikaelNyqvist** [comment]
I think that the problem might be that you haven't updated the add-on Parrot to 0.7.0. Just go to AssetLib and search for "Parrot".

**Comment by dploeger** [comment]
@Teashrock I think, @MikaelNyqvist  is right there. Did you try installing Parrot?

**Comment by Teashrock** [comment]
I think it was just my own impatience. Closing for now.
