### ISSUE TITLE
Fault tolerant Inventory.add_item() function

### ISSUE THREAD

**Issue by ThmsKnz** [deep-entertainment/egoventure#8]
The current version of the Inventory.add_item() function allows to add the same item multiple times. So in case there is a bug in one's game logic that an item can be picked up by mistake a second time, the duplicate item would show up in the inventory. I would recommend to add a safety net in the add_item() function that an item will only get added to the inventory if it is not yet in the inventory.

**Comment by dploeger** [comment]
I'd suggest we add a second parameter, that, if set to true, would check wether the item is still in the inventory. The default value of that new parameter would be true as well.

**Comment by dploeger** [comment]
You know what, forget that. We just ignore a call to that function when the item already exists in the inventory.

**Comment by ThmsKnz** [comment]
:-) 
My first thought was going into the same direction that a new optional parameter could get introduced that would allow duplicates in the inventory. But on second thoughts I came to the same conclusion that this shouldn't be supported.

In case several 'identical' items have to be picked up this can still be realized by using multiple inventory items having the same content.

**Comment by MikaelNyqvist** [comment]
You're right Thomas. There might be (at least hypothetically) situations where one picks up an identical items several times, but it wouldn't be advisable to make them appear as duplicates in the inventory for several reasons.
